name: GPT-Based Agentic PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenAI Python package
        run: pip install openai

      - name: Fetch PR diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3.diff" \
               "${{ github.event.pull_request.url }}" > pr.diff

      - name: Run GPT agentic reviewer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 gpt_review_agent.py

      - name: Comment on PR with GPT review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          COMMENT=$(python3 gpt_review_agent.py | tail -n +2 | sed ':a;N;$!ba;s/\n/\\n/g')
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -X POST \
            -d "{\"body\": \"${COMMENT}\"}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
